export const bannedPatterns = [
	/ignore previous instructions/i,
	/bypass/i,
	/jailbreak/i,
	/system prompt/i,
	/ignore all previous/i,
	/disregard previous instructions/i,
	/ignore (all )?(previous|prior) instructions?/i,
	/disregard (all )?(previous|prior) instructions?/i,
	/forget (everything|all instructions)/i,
	/override (the )?(system|rules|instructions)/i,
	/you are now (?!a helpful)/i,
	/reveal (your|the) (system|hidden) prompt/i,
	/show (me )?(your|the) instructions/i,
	/what were you told/i,
	/print (the )?(full )?prompt/i,
	/dump (your )?(instructions|config)/i,
	/act as (?!.*assistant)/i,
	/pretend to be/i,
	/you are no longer/i,
	/switch roles/i,
	/become (an?|the)/i,
	/bypass (all )?(restrictions|filters|safety)/i,
	/disable (safety|filters|moderation)/i,
	/no restrictions/i,
	/without limitations/i,
	/\bjailbreak\b/i,
	/respond (only )?in (plain text|markdown)/i,
	/do not use (json|quotes|formatting)/i,
	/ignore (the )?output format/i,
	/break (the )?format/i,
	/first .* then ignore/i,
	/after that,? ignore/i,
	/but before that/i,
	/base64/i,
	/rot13/i,
	/hex encode/i,
	/decode this/i,
	/call (any|the) function/i,
	/invoke (system|hidden)/i,
	/execute (this|the following)/i,
];
